# Generated by Django 4.2.3 on 2023-08-13 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_squashed_0005_alter_contact_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-modified_at", "name"]},
        ),
    ]
